on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: npx netlify-cli deploy --build --prod
      env:
        site_id: ${{ secrets.NETLIFY_SITE_ID }}
        auth_token: ${{ secrets.AUTH_TOKEN }}
