on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: netlify-actions/cli@v1
      env:
        site_id: ${{ secrets.NETLIFY_SITE_ID }}
        auth_token: ${{ secrets.AUTH_TOKEN }}
